config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'

  devise_for :users, path: 'devise_users'

  resources :divisions
  resources :users
end

app/models/user.rb
#
class User < ApplicationRecord
  include ApplicationHelper

  belongs_to :division, counter_cache: true
  belongs_to :manager, class_name: User.name, foreign_key: :manager_id,
                       optional: true
  has_many :managers, class_name: User.name, foreign_key: :manager_id, 
                      counter_cache: true

  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validate :validate_contract_date
  validate :validate_birthday
  validate :validate_update_role_for_admin_or_manager

  delegate :name, to: :division, prefix: true
  delegate :name, to: :manager, prefix: true

  enum role: %w[admin manager employee]
  enum gender: %w[male female other]

  scope :user_have_no_manager, lambda {
    where('manager_id IS NULL AND role = ?', User.roles[:employee])
  }

  class << self
    def random_password
      chars = (0..9).to_a + ('a'..'z').to_a + ('A'..'Z').to_a
      chars.sample(8).join
    end

    def to_csv(options = {})
      config_columns = %w[id name email role division_id]
      CSV.generate(options) do |csv|
        csv << config_columns
        all.each do |user|
          csv << user.attributes.values_at(*config_columns)
        end
      end
    end
  end

  private

  def validate_contract_date
    return unless contract_date.present?
    now = format_time Time.zone.now, :format_date
    date = format_time contract_date, :format_date
    return errors.add :error, I18n.t('.invalid_contract_date') if date > now
  end

  def validate_birthday
    return unless birthday.present?
    user_age = Time.zone.now.year - birthday.year
    return unless user_age < Settings.age_working
    errors.add :error, I18n.t('.invalid_birthday')
  end

  def validate_update_role_for_admin_or_manager
    return unless employee? && (managers_count > 0)
    errors.add :error, I18n.t('.invalid_role')
  end
end

app/controllers/users_controller.rb
#
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :load_divison, except: %i[index show destroy]
  before_action :check_role_user, only: :destroy
  before_action :load_managers, only: %i[show edit]
  before_action :load_user, only: :update
  before_action :load_all_user, only: :index

  def index
    respond_to do |format|
      format.csv { render text: @users.to_csv }
      format.xls { render text: @users.to_csv(col_sep: "\t") }
      format.html { render partial: 'more_action' } if request.xhr?
      format.html
    end
  end

  def show
    @user_have_no_managers = User.user_have_no_manager
    respond_to do |format|
      if request.xhr?
        format.html do
          render partial: 'add_owned_user',
                 locals: { user_have_no_managers: @user_have_no_managers }
        end
      end
      format.html
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new create_user_params
    if @user.save
      # SendEmailWorkerAccount.perform_async @user.id
      AccountMailer.user_account(@user).deliver_now
      flash[:success] = t '.save'
      redirect_to users_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if current_user.admin?
      exec_with_admin
    else
      update_user_params user_edit_params
    end
  end

  def destroy
    return unless @user.destroy
    flash[:success] = t '.deleted'
  end

  private

  def exec_with_admin
    if request.xhr?
      exec_request_xhr
    elsif params[:reset].present?
      reset_password_when_edit_user
    else
      update_user_params user_params
    end
  end

  def exec_request_xhr
    if params[:reset_password].present?
      multi_reset_password
    elsif params[:manager_id].present?
      @user.update_attributes manager_id: params[:manager_id]
    else
      @user.update_attributes division_id: params[:division_id]
    end
  end

  def multi_reset_password
    @user.update_attributes password: User.random_password
    PasswordMailer.user_password(@user).deliver_now
  end

  def reset_password_when_edit_user
    update_user_params(user_params.merge!(password: User.random_password))
    PasswordMailer.user_password(@user).deliver_now
  end

  def update_user_params(params)
    if @user.update_attributes params
      flash[:success] = t '.updated'
      redirect_to user_path
    else
      render :edit
    end
  end

  def create_user_params
    user_params.merge! password: User.random_password
  end

  def user_params
    params.require(:user).permit :name, :email, :gender, :birthday, :avatar,
                                 :role, :contract_date, :division_id
  end

  def user_edit_params
    params.require(:user).permit :name, :email, :gender, :birthday, :avatar
  end

  def load_divison
    @divisions = Division.all
  end

  def check_role_user
    return unless @user.admin? || @user.manager?
    flash[:danger] = t '.can_not_delete'
    redirect_to users_path
  end

  def load_managers
    @managers = @user.managers.order(updated_at: :desc).page(params[:page])
                     .per Settings.division_per_page
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user.present?
    flash.now[:danger] = t '.not_found_user'
  end

  def load_all_user
    @users = User.all.order(updated_at: :desc).includes(:division)
                 .page(params[:page]).per Settings.user_per_page
  end
end

app/views/users/_add_owned_user.html.erb
<div class="card">
  <div class="card-content" id="content-color">
    <table class="centered">
      <thead>
        <tr>
          <th>
            <div>
              <input type="checkbox" class="filled-in" id="add-user-all"></input>
              <label for="add-user-all"></label>
            </div>
          </th>
          <th><%= t ".index" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".email" %></th>
          <th><%= t ".avatar" %></th>
        </tr>
      </thead>
      <tbody>
        <% user_have_no_managers.each_with_index do |user_no_manager, index| %>
          <tr>
            <td>
              <p>
                <input type="checkbox" class="filled-in"
                  id="add-user<%= user_no_manager.id %>"
                  value="<%= user_no_manager.id %>"></input>
                <label for="add-user<%= user_no_manager.id %>"></label>
              </p>
            </td>
            <td><%= index +1 %></td>
            <td><%= link_to user_no_manager.name, user_path(user_no_manager) %></td>
            <td><%= user_no_manager.email %></td>
            <td>
              <% if user_no_manager.avatar? %>
                <%= image_tag user_no_manager.avatar, size: Settings.avatar_index_size,
                  class: "circle" %>
              <% else %>
                <%= image_tag Settings.default_avatar, class: "circle",
                  size: Settings.avatar_index_size %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div id="fixed-button">
      <div class="card teal lighten-4">
        <div class="card-content">
          <%= button_tag t(".ok"), class: "btn ok-add-user" %>
          <%= button_tag t(".cancel"), class: "btn close-add-user" %>
        </div>
      </div>
    </div>
</div>
</div>

app/views/users/_employees_manage.html.erb
<div class="card">
  <div class="card-content teal lighten-2">
    <h4 class="center-align upper-case"><%= "employees" %></h4>
  </div>
  <div class="card-action" id="content-color">
    <table class="centered">
      <thead>
        <tr>
          <th><%= t ".index" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".email" %></th>
          <th><%= t ".avatar" %></th>
        </tr>
      </thead>
      <tbody>
        <% managers.each_with_index do |manager, index| %>
          <tr>
            <td><%= index +1 %></td>
            <td><%= link_to manager.name, user_path(manager) %></td>
            <td><%= manager.email %></td>
            <td>
              <% if manager.avatar? %>
                <%= image_tag manager.avatar, size: Settings.avatar_index_size,
                  class: "circle" %>
              <% else %>
                <%= image_tag Settings.default_avatar, class: "circle",
                  size: Settings.avatar_index_size %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate managers %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_message" , object: f.object %>
  <div class="row">
    <div class="col s3"></br>
      <% if @user.avatar? %>
        <%= image_tag @user.avatar, size: Settings.avatar_create_size %>
      <% else %>
        <%= image_tag Settings.default_avatar, size: Settings.avatar_create_size %>
      <% end %>
      <span>
        <%= f.file_field :avatar, accept: Settings.image_format_accept %>
      </span>
    </div>
    <% if can? :manage, :all %>
      <div class="col s4">
    <% else %>
      <div class="col s9">
    <% end %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :birthday %>
        <%= f.text_field :birthday, class: "datepicker",
          value: format_time(@user.birthday, :format_date),
          id: "user-birthday" %>
      </div>
      <div class="form">
        <%= f.label :gender, class: "col-md-3 control-label" %>
        <p>
          <% User.genders.keys.each do |key| %>
            <%= f.radio_button :gender, t(".value_#{key}"), class: "with-gap" %>
            <label for="user_gender_<%= "#{key}" %>">
              <%= t(".value_#{key}") %>
            </label>
            &nbsp;&nbsp;&nbsp;&nbsp;
          <% end %>
        </p>
      </div>
    </div>
    <% if can? :manage, :all %>
      <div class="col s4">
        <div class="form">
          <div class="field">
            <%= f.label :contract_date %>
            <%= f.text_field :contract_date, class: "datepicker",
            value: format_time(@user.contract_date, :format_date),
            id: "contract-date" %>
          </div>
          <div class="input-field">
            <%= f.select :division_id, @divisions.collect {|c| [c.name, c.id]},
              {selected: @user.division_id, include_blank: false}, class: "select" %>
          </div></br>
          <%= f.label :role, class: "col-md-3 control-label" %>
          <p>
            <% User.roles.keys.each do |key| %>
              <%= f.radio_button :role, t(".value_#{key}"), class: "with-gap" %>
              <label for="user_role_<%= "#{key}" %>">
                <%= t(".value_#{key}") %>
              </label>
              &nbsp;&nbsp;&nbsp;&nbsp;
            <% end %>
          </p></br>
          <p>
            <label><%= t ".reset_password" %></label></br>
            <input type="checkbox" name="reset" class="filled-in" id="reset-password"
              value="1"></input>
            <label for="reset-password" id="reset-answer"><%= t ".no" %></label>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="btn-center">
    <%= f.submit t(".submit"), class: "btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/users/_more_action.html.erb
<div class="card-panel blue-grey lighten-5">
  <span class="teal-text">
    <p class="flex-action">
      <i class="material-icons">file_download</i>
      <%= t "users.index.export_users" %>
      <%= link_to "CSV", users_path(format: "csv") %> |
      <%= link_to "Excel", users_path(format: "xls") %>
    </p>
    <li class="divider"></li>
    <p><a class="flex-action" href="<%= new_user_path %>">
      <i class="material-icons">add</i><%= t "users.index.create" %>
    </a></p>
    <li class="divider"></li>
    <p><a class="flex-action reset-password" href="javascript:void(0)">
      <i class="material-icons">autorenew</i>
      <%= t "users.index.reset_password" %>
    </a></p>
    <li class="divider"></li>
    <p><a class="flex-action delete-employees" href="javascript:void(0)">
      <i class="material-icons">delete</i>
      <%= t "users.index.delete_employees" %>
    </a></p>
  </span>
</div>

app/views/users/edit.html.erb
<div class="card">
  <div class="card-image">
    <%= image_tag "employees.png", class: "component-image" %>
    <span class="card-title"><%= @user.name %></span>
  </div>
  <div class="card-content" id="content-color">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".all_employees") %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "employees.png", class: "component-image" %>
      <span class="card-title"><%= t ".all_employees" %></span>
      <% if can? :manage, :all %>
        <a class="more-action-user btn-floating btn-large halfway-fab amber
          accent-4 tooltipped" href="javascript:void(0)" data-position="left"
          data-tooltip="<%= t ".more_action" %>" >
          <i class="medium material-icons">more_vert</i>
        </a>
        <div class="multi-action col s3 offset-s9"></div>
      <% end %>
    </div>
    <div class="card-content" id="content-color">
      <table class="centered">
        <thead>
          <tr>
            <% if can? :manage, :all %>
              <th>
                <div>
                  <input type="checkbox" name="reset_all" class="filled-in"
                    id="reset-password-all" disabled="disabled"></input>
                  <label for="reset-password-all"></label>
                </div>
              </th>
            <% end %>
            <th><%= t ".index" %></th>
            <th><%= t ".name" %></th>
            <th><%= t ".email" %></th>
            <th><%= t ".division" %></th>
            <th><%= t ".avatar" %></th>
            <% if can? :manage, :all %>
              <th><%= t ".action" %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @users.each_with_index do |user, index| %>
            <tr id="user<%= user.id %>">
              <% if can? :manage, :all %>
                <td>
                  <p>
                    <input type="checkbox" name="reset" class="filled-in"
                      id="reset-password<%= user.id %>" value="<%= user.id %>"
                      disabled="disabled"></input>
                    <label for="reset-password<%= user.id %>"></label>
                  </p>
                </td>
              <% end %>
              <td><%= index +1 %></td>
              <td>
                <%= link_to user.name, user_path(user), data: {turbolinks: false} %>
              </td>
              <td><%= user.email %></td>
              <td><%= user.division_name %></td>
              <td>
                <% if user.avatar? %>
                  <%= image_tag user.avatar, size: Settings.avatar_index_size,
                    class: "circle" %>
                <% else %>
                  <%= image_tag Settings.default_avatar, class: "circle",
                    size: Settings.avatar_index_size %>
                <% end %>
              </td>
              <% if can? :manage, :all %>
                <td>
                  <a href="<%= user_path(user) %>" data-position="top"
                    class="btn-floating green tooltipped"
                    data-tooltip="<%= t ".detail" %>" data-turbolinks="false">
                    <i class="material-icons">details</i>
                  </a>
                  <% unless user.admin? %>
                    <a data-position="top" value="<%= user.id %>"
                      class="btn-floating red tooltipped delete-employee"
                      data-tooltip="<%= t ".delete" %>">
                      <i class="material-icons">delete</i>
                    </a>
                  <% end %>
                </td>
              <% end %>
            </tr>
            <input type="hidden" value="<%= user.role %>"
              class="user-role<%= user.id %>">
          <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
      <div id="fixed-button" class="hidden-fixed-button">
        <div class="card teal lighten-4">
          <div class="card-content">
            <%= button_tag t(".ok"), class: "btn btn-action-allowed" %>
            <%= button_tag t(".cancel"),
              class: "btn btn-action-deny deep-orange lighten-1" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".new_user") %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "employees.png", class: "component-image" %>
      <span class="card-title"><%= t ".new_user" %></span>
    </div>
    <div class="card-content" id="content-color">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, "#{@user.name}" %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "employees.png", class: "component-image" %>
      <span class="card-title"><%= @user.name %></span>
    </div>
    <div class="card-content" id="content-color">
      <div class="row">
        <div class="col s6" id="content-color">
          <b><p><%= t ".avatar" %></p></b>
          <% if @user.avatar? %>
            <%= image_tag @user.avatar, size: Settings.avatar_show_size %>
          <% else %>
            <%= image_tag Settings.default_avatar,
              size: Settings.avatar_show_size %>
          <% end %>
        </div>
        <div class="col s6" id="content-color">
          <b><%= t ".name" %></b><%= @user.name %></br></br>
          <b><%= t ".email" %></b><%= @user.email %></br></br>
          <b><%= t ".role" %></b><%= @user.role %></br></br>
          <b><%= t ".birthday" %></b>
          <%= format_time(@user.birthday, :format_date) %><br></br>
          <b><%= t ".gender" %></b><%= @user.gender %></br></br>
          <b><%= t ".contract_date" %></b>
          <%= format_time(@user.contract_date, :format_date) %></br></br>
          <b><%= t ".division" %></b><%= @user.division_name %></br></br>
          <% if @user.manager.present? %>
            <b><%= t ".manager" %></b><%= @user.manager_name %>
          <% end %>
        </div>
      </div>
      <% if can? :update, @user %>
        <%= link_to t(".edit_profile"), edit_user_path(@user),
          class: "btn waves-effect waves-light", data: {turbolinks: false} %>
        <% if @user.manager? || @user.admin? %>
          <%= button_tag t(".add_user"), class: "btn add-owned-employee" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="show-user-have-no-manager"></div>
<% if @managers.present? %>
  <%= render "employees_manage", managers: @managers %>
<% end %>
<input type="hidden" value="<%= @user.id %>" id="manager-id">
<input type="hidden" value="<%= @user_have_no_managers.size %>" id="number-user">