config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'

  devise_for :users, path: 'devise_users'

  resources :divisions
  resources :users
end

app/models/division.rb
#
class Division < ApplicationRecord
  has_many :users

  validates :name, presence: true
  validates :description, presence: true

  ATTR_PARAMS = %i[name description].freeze

  scope :all_except, ->(id) { where.not id: id }

  def self.to_csv(options = {})
    config_columns = %w[id name description]
    CSV.generate(options) do |csv|
      csv << config_columns
      all.each do |division|
        csv << division.attributes.values_at(*config_columns)
      end
    end
  end
end

app/controllers/divisions_controller.rb
#
class DivisionsController < ApplicationController
  load_and_authorize_resource
  before_action :check_exist_users, only: :destroy
  before_action :load_all_division, only: :index

  def index
    respond_to do |format|
      format.csv { render text: @divisions.to_csv }
      format.xls { render text: @divisions.to_csv(col_sep: "\t") }
      format.html { render partial: 'more_action' } if request.xhr?
      format.html
    end
  end

  def show
    @employees_in_div = @division.users.order(updated_at: :desc)
                                 .page(params[:page])
                                 .per Settings.division_per_page
    @divisions = Division.all_except(@division.id)
  end

  def new
    @division = Division.new
  end

  def create
    @division = Division.new division_params
    if @division.save
      flash[:success] = t '.save'
      redirect_to divisions_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @division.update_attributes division_params
      redirect_to divisions_path
      flash[:success] = t '.updated'
    else
      render :edit
    end
  end

  def destroy
    return unless @division.destroy
    flash[:success] = t '.deleted'
  end

  private

  def division_params
    params.require(:division).permit Division::ATTR_PARAMS
  end

  def check_exist_users
    return unless @division.users.any?
    flash[:danger] = t '.can_not_delete'
    redirect_to divisions_path
  end

  def load_all_division
    @divisions = Division.all.order(created_at: :desc).page(params[:page])
                         .per Settings.division_per_page
  end
end

app/views/divisions/_employees_in_division.html.erb
<div class="card">
  <div class="card-content teal lighten-2">
    <h4 class="center-align upper-case">
      <%= t ".employee_in" %> <%= "#{div.name}" %>
    </h4>
  </div>
  <div class="card-action" id="content-color">
    <% if can? :manage, :all %>
      <%= button_tag t(".move"), class: "btn move-employees" %>
    <% end %>
    <table class="centered">
      <thead>
        <tr>
          <% if can? :manage, :all %>
            <th>
              <div>
                <input type="checkbox" class="filled-in" id="move-all"
                  disabled="disabled"></input>
                <label for="move-all"></label>
              </div>
            </th>
          <% end %>
          <th><%= t ".index" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".email" %></th>
          <th><%= t ".avatar" %></th>
          <% if can? :manage, :all %>
            <th><%= t "divisions.index.action" %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% employees.each_with_index do |employee, index| %>
          <tr id="employee<%= employee.id %>">
            <% if can? :manage, :all %>
              <td>
                <p>
                  <input type="checkbox" class="filled-in" disabled="disabled"
                    id="move<%= employee.id %>" value="<%= employee.id %>">
                  </input>
                  <label for="move<%= employee.id %>"></label>
                </p>
              </td>
            <% end %>
            <td><%= index +1 %></td>
            <td><%= link_to employee.name, user_path(employee) %></td>
            <td><%= employee.email %></td>
            <td>
              <% if employee.avatar? %>
                <%= image_tag employee.avatar, size: Settings.avatar_index_size,
                  class: "circle" %>
              <% else %>
                <%= image_tag Settings.default_avatar, class: "circle",
                  size: Settings.avatar_index_size %>
              <% end %>
            </td>
            <% if (can? :manage, :all) || (can? :update, div) %>
              <td>
                <% unless employee.admin? || employee.manager? %>
                  <a data-position="top"
                    class="btn-floating red tooltipped delete-employee-in-div"
                    data-tooltip="<%= t ".delete" %>" value="<%= employee.id %>">
                    <i class="material-icons">delete</i>
                  </a>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate employees %>
    <div id="fixed-button" class="hidden-fixed-button">
      <div class="card teal lighten-4">
        <div class="card-content">
          <a class="btn modal-trigger btn-action-allowed">
            <%= t ".move_to" %>
          </a>
          <%= button_tag t(".cancel"),
            class: "btn btn-action-deny deep-orange lighten-1" %>
        </div>
      </div>
    </div>
    <div id="modal-move-to-division" class="modal">
      <div class="modal-content">
        <h4><%= t ".choose_division" %></h4>
        <% divisions.each do |division| %>
          <p>
            <input name="group1" type="radio" id="division<%= division.id %>"
              value="<%= division.id %>" class="with-gap" />
            <label for="division<%= division.id %>">
              <%= division.name %>
            </label>
          </p>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= button_tag t(".ok"), class: "btn btn-allow-move btn-center" %>
      </div>
    </div>
  </div>
</div>

app/views/divisions/_form.html.erb
<%= form_for @division do |f| %>
  <%= render "shared/error_message" , object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit t(".submit"), class: "btn waves-effect waves-light" %>
<% end %>

app/views/divisions/_more_action.html.erb
<div class="card-panel blue-grey lighten-5">
  <span class="teal-text">
    <p>
      <%= t "divisions.index.export_divisions" %>
      <%= link_to "CSV", divisions_path(format: "csv") %> |
      <%= link_to "Excel", divisions_path(format: "xls") %>
    </p>
    <li class="divider"></li>
    <p><a class="flex-action" href="<%= new_division_path %>">
      <i class="material-icons">add</i><%= t "divisions.index.create" %>
    </a></p>
  </span>
</div>

app/views/divisions/edit.html.erb
<% provide :title, t(".edit_division") %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "division.jpg", class: "component-image" %>
      <span class="card-title"><%= "#{@division.name}" %></span>
    </div>
    <div class="card-content" id="content-color">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/divisions/index.html.erb
<% provide :title, t(".all_divisions") %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "division.jpg", class: "component-image" %>
      <span class="card-title"><%= t ".all_divisions" %></span>
      <% if can? :manage, :all %>
        <a class="more-action btn-floating btn-large halfway-fab amber accent-4
          tooltipped" href="javascript:void(0)" data-position="left"
          data-tooltip="<%= t ".more_action" %>" >
          <i class="medium material-icons">more_vert</i>
        </a>
        <div class="multi-action col s3 offset-s9"></div>
      <% end %>
    </div>
    <div class="card-content" id="content-color">
      <% if can? :manage, :all %>
      <% end %>
      <table class="centered">
        <thead>
          <tr>
            <th><%= t ".index" %></th>
            <th><%= t ".name" %></th>
            <th><%= t ".number_of_member" %></th>
            <% if can? :manage, :all %>
              <th><%= t ".action" %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @divisions.each_with_index do |division, index| %>
            <tr id="division<%= division.id %>">
              <td><%= index +1 %></td>
              <td><%= link_to division.name, division_path(division),
                data: {turbolinks: false} %></td>
              <td id="member<%= division.id %>" value="<%= division.users.count %>">
                <%= division.users_count %>
              </td>
              <% if can? :manage, :all %>
                <td>
                  <a href="<%= division_path(division) %>" data-position="top"
                    class="btn-floating green tooltipped"
                    data-tooltip="<%= t ".detail" %>" data-turbolinks="false">
                    <i class="material-icons">details</i>
                  </a>
                  <a data-position="top"
                    class="btn-floating red tooltipped delete-division"
                    data-tooltip="<%= t ".delete" %>" value="<%= division.id %>">
                    <i class="material-icons">delete</i>
                  </a>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @divisions %>
    </div>
  </div>
</div>

app/views/divisions/new.html.erb
<% provide :title, t(".new_division") %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "division.jpg", class: "component-image" %>
      <span class="card-title"><%= t ".new_division" %></span>
    </div>
    <div class="card-content" id="content-color">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/divisions/show.html.erb
<% provide :title, "#{@division.name}" %>
<div class="row">
  <div class="card">
    <div class="card-image">
      <%= image_tag "division.jpg", class: "component-image" %>
      <span class="card-title"><%= @division.name %></span>
    </div>
    <div class="card-content" id="content-color">
      <div class="row">
        <div class="col s8">
          <% if @employees_in_div.present? %>
            <%= render "employees_in_division", employees: @employees_in_div,
              divisions: @divisions, div: @division %>
          <% end %>
        </div>
        <div class="col s4" id="detail-division">
          <h3 class="center-align"><%= t ".information" %></h3>
          <li class="divider"></li></br>
          <b><p><%= t ".name" %></p></b>
          <h4><%= @division.name %></h4>
          <b><%= t ".number_employee" %></b>
          <h4><%= @division.users_count %></h4>
          <b><%= t ".description" %></b>
          <h4>
            <%= @division.description %>
          </h4>
          <% if (can? :manage, :all) || (can? :update, @division) %>
            <li class="divider"></li></br>
            <a href="<%= edit_division_path(@division) %>" data-position="right"
              class="btn-floating orange tooltipped edit-division modal-trigger"
              value="<%= @division.id %>" data-tooltip="<%= t ".edit" %>">
              <i class="material-icons">edit</i>
            </a>
          <% end %>
        </div>
      </div>
      <div id="modal-edit-division" class="modal">
        <div class="modal-content">
          <h4 class="center-align"><%= "Edit #{@division.name}" %></h4>
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>