config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'

  devise_for :users, path: 'devise_users'

  resources :divisions
  resources :users
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col s4 center-align">
      <ul>
        <li class="footer-company">
          <%= t "static_pages.home.company_name" %>
        </li>
        <li class="footer-slogan"><%= t ".slogan" %></li>
      </ul>
    </div>
    <div class="col s4">
      <ul>
        <li class="upper-case">
          <i class="material-icons">contacts</i><%= t ".contact_us" %>
        </li>
        <li class="divider"></li>
      </ul>
      <ul>
        <li>
          <p><i class="material-icons">location_on</i><%= t ".location" %></p>
        </li>
        <li>
          <p><i class="material-icons">phone_android</i><%= t ".phone" %><p>
        </li>
        <li>
          <p><i class="material-icons">contact_mail</i><%= t ".phone" %></p>
        </li>
      </ul>
    </div>
    <div class="col s4">
      <ul>
        <li class="upper-case">
          <i class="material-icons">attach_file</i><%= t ".link" %>
        </li>
        <li class="divider"></li>
      </ul>
      <ul>
        <div class="row">
          <div class="col s6">
            <li><p><%= "History and Mission" %></li></p>
            <li><p><%= "Why Rikkeisoft" %></li></p>
            <li><p><%= "News" %></li></p>
            <li><p><%= "Testimonials" %></li></p>
          </div>
          <div class="col s6">
            <li><p><%= "History and Mission" %></li></p>
            <li><p><%= "Why Rikkeisoft" %></li></p>
            <li><p><%= "News" %></li></p>
            <li><p><%= "Testimonials" %></li></p>
          </div>
        </div>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
    <%= t ".copyright" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper" id="menu">
      <ul class="left hide-on-med-and-down">
        <% if current_user.present? %>
          <li><%= link_to "Home", root_path, data: {turbolinks: false} %></li>
        <% end %>
      </ul>
      <ul class="right hide-on-med-and-down">
        <% if current_user.present? %>
          <li><%= link_to t(".division"), divisions_path %></li>
          <li>
            <%= link_to t(".employees"), users_path, data: {turbolinks: false} %>
          </li>
          <li>
            <a class="dropdown-button" href="#" data-activates="dropdown"
              data-beloworigin="true">
              <%= current_user.name %>
              <i class="material-icons right">arrow_drop_down</i>
            </a>
            <ul id="dropdown" class="dropdown-content">
              <li>
                <%= link_to t(".profile"), current_user,
                  data: {turbolinks: false} %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), destroy_user_session_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <a class="modal-trigger login-btn"><%= t ".sign_in" %></a>
            <%= render "devise/sessions/form_login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_present.html.erb
<div class="slider fullscreen">
  <ul class="slides">
    <li>
      <%= image_tag Settings.present2 %>
      <div class="caption center-align text-under-image">
        <h2><span><%= t ".company_name" %></span></h2></br>
        <h5 class="light grey-text text-lighten-3">
          <span><%= t ".project_name" %></span>
        </h5>
      </div>
    </li>
    <li>
      <%= image_tag Settings.present1 %>
      <div class="caption left-align text-under-image">
        <h2><span><%= t ".slogan" %></span></h2></br>
        <h5 class="light grey-text text-lighten-3">
          <span><%= t ".present" %></span>
        </h5>
      </div>
    </li>
    <li>
      <%= image_tag Settings.present3 %>
      <div class="caption left-align text-under-image">
        <h2><span><%= t ".mission" %></span></h2></br>
        <h5 class="light grey-text text-lighten-3">
          <span><%= t ".mission_detail" %></span>
        </h5>
      </div>
    </li>
  </ul>
</div>
<div class="buttons-wrapper">
  <div class="row center">
    <a class="btn modal-trigger login-btn amber accent-4">
      <i class="medium material-icons">person</i> <%= t ".sign_in" %>
    </a>
  </div>
</div>
<%= render "devise/sessions/form_login" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= t ".title" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link rel="icon" type="image/png" href="/assets/rikkei-logo.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <% if current_user.present? %>
      <header>
        <%= render "layouts/header" %>
      </header>
      <container>
        <%= yield %>
        <a id="back-to-top"><span></span></a>
      </container>
      <footer class="page-footer" id="menu">
        <%= render "layouts/footer" %>
      </footer>
    <% else %>
      <%= render "layouts/present" %>
    <% end %>
  </body>
</html>